### ISSUE TITLE
FileNotFoundError for gym3/internal/font.bin

### ISSUE THREAD

**Issue by w-hat** [openai/gym3#1]
Procgen environments are crashing:

```sh
$ python3 -m procgen.interactive --env-name bigfish
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/greg/.local/lib/python3.6/site-packages/procgen/interactive.py", line 82, in <module>
    main()
  File "/home/greg/.local/lib/python3.6/site-packages/procgen/interactive.py", line 78, in main
    ia.run()
  File "/home/greg/.local/lib/python3.6/site-packages/gym3/interactive.py", line 106, in run
    self._draw()
  File "/home/greg/.local/lib/python3.6/site-packages/gym3/interactive.py", line 175, in _draw
    self._draw_step()
  File "/home/greg/.local/lib/python3.6/site-packages/gym3/interactive.py", line 149, in _draw_step
    size_px=16,
  File "/home/greg/.local/lib/python3.6/site-packages/gym3/internal/renderer.py", line 274, in draw_text
    image = _convert_ascii_to_rgba(arr, size_px=size_px)
  File "/home/greg/.local/lib/python3.6/site-packages/gym3/internal/renderer.py", line 37, in _convert_ascii_to_rgba
    FONT = np.load(os.path.join(SCRIPT_DIR, "font.bin"))
  File "/home/greg/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/greg/.local/lib/python3.6/site-packages/gym3/internal/font.bin'
```

All 16 procgen environments crash with the same error after rendering a single frame.  Am I missing something or is gym3 trying to use a font file that's not open sourced?

**Comment by christopherhesse** [comment]
Thanks for the bug report, this should be fixed in `gym==0.3.1`.  The font file was in the repo, just not marked to be included in the packaged library.
